#!/usr/bin/env node

var app = require('../server/server');
var port = process.env.PORT || 9090;

app.set('port', port);

var modeChecker = (port === 9090) ? devMode() : prodMode();

function devMode() {
  return 'Running in Development Mode'
}

function prodMode() {
  return 'Running in Production Mode'
}

app.listen(port)
console.log('HUGE App Server is running on port:' + port + ' ' +
  modeChecker);
